# Configuration de la datasource PostgreSQL
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=greentrip
%prod.quarkus.datasource.password=greentrip_secure_password
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/greentrip

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=greentrip
%dev.quarkus.datasource.password=greentrip_secure_password
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/greentrip

# Stratégie Hibernate ORM
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Activation d'OpenAPI et Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.path=/openapi
